### PR TITLE
Clean up semi-colons, whitespace and comments

### PR DESCRIPTION
**Pull request by ShannonPaige**
**What's this PR do?**
Clean up semi-colons, whitespace and un-needed comments.

**Where should the reviewer start?**
It doesn't matter.

**How should this be manually tested?**
Clone the repo, run rails s in the terminal to start up a server then create an idea and delete an idea to demonstrate that the functionality is still there.

**Any background context you want to provide?**
I was one of the people who thought "semi-colons optional" meant I could use them willy-nilly. I realize now it means I can use them or not - but be consistent! I have since joined the semi-colons forever movement.

**What gif best describes this PR or how it makes you feel?**
WHAS

@hectorhuertas
@rrgayhart

### CODE REVIEW

**Comment by rrgayhart** [comment]
:+1:

**Comment by hectorhuertas** [comment]
I also went the same path, semicolons forever. ;;;;

The refactoring is pretty good, but the gif is PERFECT.

**Comment by hectorhuertas** [comment]
Ready to merge! :+1:

**Comment by ShannonPaige** [comment]
Thank you for the feedback!!

**Pull request merged**
